print len(open('train1.txt','r').readlines())
print len(open('train2.txt','r').readlines())
print len(open('train3.txt','r').readlines())
print len(open('train4.txt','r').readlines())
print len(open('train5.txt','r').readlines())
print len(open('train6.txt','r').readlines())
print len(open('namelist.txt','r').readlines())

print len(open('set1.txt','r').readlines())
print len(open('set2.txt','r').readlines())
print len(open('set3.txt','r').readlines())
print len(open('set4.txt','r').readlines())
print len(open('set5.txt','r').readlines())
print len(open('set6.txt','r').readlines())
print len(open('featureid.txt','r').readlines())
